# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ json, html ], fallback_format: ~, prefer_extension: false }
    #media_type:
    #    version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'

  body_converter:
    enabled: true
    validate: true

  view:
    view_response_listener: 'force'
    formats:
      xml: true
      json: true
    templating_formats:
      html: true
    force_redirects:
      html: true
    failed_validation: HTTP_BAD_REQUEST
    default_engine: none
    mime_types:
      json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']

  exception:
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    messages:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
  allowed_methods_listener: true
  access_denied_listener:
    json: true
  routing_loader:
    default_format: json
