framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~

    php_errors:
        log: true

    templating: { engines: ['twig'] }

sensio_framework_extra:
    view: { annotations: true }
